# This file is a part of the detect-pythons project.
# https://github.com/kurtmckee/detect-pythons
# Copyright 2023-2025 Kurt McKee <contactme@kurtmckee.org>
# SPDX-License-Identifier: MIT

author: "Kurt McKee"
name: "Detect installed Python interpreters"
description: |
  Generate a robust cache-busting key based on
  installed Python interpreters, versions, and target architectures.
branding:
  icon: "archive"
  color: "green"

inputs:
  identifiers-filename:
    description: |
      A filename to write the ``python-identifiers`` output to.
      Suitable for use in with the ``hashFiles`` function.

      To prevent any file from being written, use a blank string.
    required: false
    default: ".python-identifiers"

outputs:
  python-identifiers:
    description: |
      A string of sorted Python identifiers.

      In most cases the identifiers will be paths,
      but for system Pythons, 'sysconfig.get_config_var("EXT_SUFFIX")' will be included.

      The string will be separated by OS-specific PATH separators;
      ":" is used on Linux and macOS, and ";" is used on Windows.
    value: "${{ steps.final-step.outputs.python-identifiers }}"

runs:
  using: "composite"
  steps:
    - name: "Detect Pythons on Linux / macOS"
      id: "linux"
      if: "runner.os != 'Windows'"
      shell: "bash"
      run: 'bash ${GITHUB_ACTION_PATH}/src/detect_pythons/detector.sh > ${GITHUB_OUTPUT}'

    - name: "Detect Pythons on Windows"
      id: "windows"
      if: "runner.os == 'Windows'"
      shell: "pwsh"
      run: '& $env:GITHUB_ACTION_PATH\src\detect_pythons\detector.ps1 > $env:GITHUB_OUTPUT'

    - name: "Output"
      id: "final-step"
      shell: "bash"
      run: |
        COMBINED='${{ steps.linux.outputs.python-identifiers }}${{ steps.windows.outputs.python-identifiers }}'
        echo "python-identifiers=${COMBINED}" > "$GITHUB_OUTPUT"
        if [ ! -z '${{ inputs.identifiers-filename }}' ]; then
            echo "Writing Python identifiers to '${{ inputs.identifiers-filename }}'"
            echo "${COMBINED}" > '${{ inputs.identifiers-filename }}'
        fi
